# Generated by Django 2.2.6 on 2019-10-22 07:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191021_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\MiniMind\\DEV\\mysite\\django\\static_cdn'), upload_to=''),
        ),
    ]
